version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: freelanceflow-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: freelanceflow
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./server/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app:
    build: .
    container_name: freelanceflow-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/freelanceflow
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./server/.env:/app/server/.env:ro

  nginx:
    image: nginx:alpine
    container_name: freelanceflow-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app

volumes:
  mongodb_data:
